import { shareAll, withNativeFederation } from '@angular-architects/native-federation/config';

export default withNativeFederation({
  name: 'portfolio',
  shared: {
    ...shareAll({ singleton: true, strictVersion: true, requiredVersion: 'auto' }),
  },
  skip: [
    'rxjs/ajax',
    'rxjs/fetch',
    'rxjs/testing',
    'rxjs/webSocket',
    '@core/utils/navigation',
    '@shared/components/language-switcher/language-switcher',
    '@shared/components/icon/icon',
    '@shared/components/status-dot/status-dot',
    '@shared/components/logo/logo',
    '@core/services/status',
    '@core/services/ai',
    '@core/models/ai',
    '@core/services/language',
    '@shared/pipes/safe-html',
    '@core/services/platform',
    '@core/models/form',
    '@shared/directives/feature-flag',
    '@features/skills/skills',
    '@features/hero/hero',
    '@features/experience/experience',
    '@core/services/session',
    '@core/services/seo',
    '@core/constants/sections',
    '@core/config/seo',
    '@core/constants/feature-flags',
    '@core/guards/admin',
  ],
  features: {
    ignoreUnusedDeps: true,
    ignoreInternalPaths: true,
  },
});
